POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpY3RvciIsImlkIjoiNWRmYmZkZTdjYWY0M2Q2NDg2MzhlNWYxIiwiaWF0IjoxNTc2OTQzMTI4fQ.IgLchjKKQiRdKnLMit680znBeSJGHgqbuxJI5IUxCDo

{
  "title": "I love lego train",
  "author": "Daniel Molero",
  "url": "http://daniel-molero.com/blog/",
  "likes": 700
}

###

GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/unknown

###

GET http://localhost:3003/api/blogs/1